import { useCallback, useEffect, useState } from 'react';

import { AutomaticOrderPanel } from './AutomaticOrderPanel';
import { OrdersPanel } from './OrdersPanel';
import { PositionPanel } from './PositionPanel';
import { PriceChart } from './PriceChart';
import { TerminalHeader } from './TerminalHeader';
import { TradeHistory } from './TradeHistory';
import { TradingPanel } from './TradingPanel';
import { WalletPanel } from './WalletPanel';
import { DEFAULT_EXCHANGE, DEFAULT_SYMBOL } from '@/config/instrument';
import { useAccount } from '@/hooks/useAccount';
import { useLivePrice } from '@/hooks/useLivePrice';

type Tab = 'orders' | 'trades';

/**
 * The trading terminal.
 *
 * Two data paths, deliberately separate:
 *
 * * **WebSocket** carries the live price -- one stream, no polling.
 * * **REST** carries commands and account state, refetched after an order
 *   fills so every panel updates from one consistent set of reads.
 */
export function Terminal() {
  const { tick, automaticOrderEvent, status, connection, attempt, isStale, reconnect } =
    useLivePrice();
  const markPrice = tick?.last_price ?? null;

  const {
    wallet,
    position,
    portfolio,
    orders,
    trades,
    loading,
    error,
    needsWallet,
    refresh,
    createWallet,
  } = useAccount(markPrice);

  const [tab, setTab] = useState<Tab>('orders');
  // Bumped whenever the automatic-order list needs reloading.
  const [automationToken, setAutomationToken] = useState(0);

  // A fill changes the wallet, the position and both histories at once, so
  // everything is reloaded together rather than patched piecemeal.
  const handleFilled = useCallback(() => {
    void refresh();
    // A manual fill can retire or clamp a stop-loss server-side, so the
    // trigger list is reloaded alongside the account panels.
    setAutomationToken((token) => token + 1);
  }, [refresh]);

  // A trigger fired on the backend: position, wallet, P&L and both histories
  // have all moved. Reload everything -- no page refresh needed.
  useEffect(() => {
    if (automaticOrderEvent === null) return;
    void refresh();
    setAutomationToken((token) => token + 1);
  }, [automaticOrderEvent, refresh]);

  return (
    <div className="terminal">
      <TerminalHeader
        tick={tick}
        status={status}
        connection={connection}
        attempt={attempt}
        isStale={isStale}
        onReconnect={reconnect}
      />

      {tick?.is_mock && (
        <p className="banner banner--warning">
          Simulated market data — generated by a random walk, with no
          relationship to the real market.
        </p>
      )}

      {error && (
        <p className="banner banner--error">
          {error}{' '}
          <button type="button" className="link" onClick={() => void refresh()}>
            Retry
          </button>
        </p>
      )}

      <div className="terminal__body">
        <div className="terminal__main">
          <PriceChart
            symbol={tick?.symbol ?? DEFAULT_SYMBOL}
            exchange={tick?.exchange ?? DEFAULT_EXCHANGE}
            tick={tick}
          />

          <PositionPanel
            position={position}
            portfolio={portfolio}
            currentPrice={markPrice}
          />

          <section className="panel">
            <header className="panel__header">
              <div className="tabs" role="tablist">
                <button
                  type="button"
                  role="tab"
                  aria-selected={tab === 'orders'}
                  className={`tab ${tab === 'orders' ? 'tab--active' : ''}`}
                  onClick={() => setTab('orders')}
                >
                  Orders{orders.length > 0 ? ` (${orders.length})` : ''}
                </button>
                <button
                  type="button"
                  role="tab"
                  aria-selected={tab === 'trades'}
                  className={`tab ${tab === 'trades' ? 'tab--active' : ''}`}
                  onClick={() => setTab('trades')}
                >
                  Trades{trades.length > 0 ? ` (${trades.length})` : ''}
                </button>
              </div>

              <button
                type="button"
                className="chip"
                onClick={() => void refresh()}
                disabled={loading}
              >
                {loading ? 'Loading…' : 'Refresh'}
              </button>
            </header>

            {tab === 'orders' ? (
              <OrdersPanel orders={orders} />
            ) : (
              <TradeHistory trades={trades} />
            )}
          </section>
        </div>

        <aside className="terminal__side">
          <TradingPanel
            referencePrice={markPrice}
            position={position}
            disabled={needsWallet}
            onFilled={handleFilled}
          />

          <AutomaticOrderPanel
            position={position}
            referencePrice={markPrice}
            disabled={needsWallet}
            refreshToken={automationToken}
            onChanged={() => setAutomationToken((token) => token + 1)}
          />

          <WalletPanel
            wallet={wallet}
            portfolio={portfolio}
            needsWallet={needsWallet}
            onCreateWallet={() => void createWallet()}
          />
        </aside>
      </div>

      <footer className="terminal__footer muted">
        Paper trading only · virtual money · no orders reach any exchange
      </footer>
    </div>
  );
}
