"""Mock market-data provider.

**This provider invents prices.** It exists so the real-time pipeline can be
developed and demonstrated without depending on an external feed, market hours
or a broker subscription. Nothing it returns has any connection to the actual
market.

Selected with ``MARKET_DATA_PROVIDER=mock``. Every quote it produces carries
``is_mock=True`` and ``provider="mock"``, the capabilities report says so, and
the application logs a warning at startup -- so mock data can never be
mistaken for live data further up the stack.

Unlike the Yahoo provider it *does* support both order-book depth and push
streaming, because it synthesises them. That makes it the only way to exercise
``subscribe_live_data`` end to end.
"""

import asyncio
import random
from collections.abc import AsyncIterator
from datetime import UTC, datetime, timedelta
from decimal import Decimal

from app.core.config import settings
from app.core.logging import get_logger
from app.market_data.base import MarketDataProvider
from app.schemas.market_data import Candle, Interval, ProviderCapabilities, Quote
from app.trading.pnl import to_money

logger = get_logger(__name__)

_BPS = Decimal("10000")

_INTERVAL_SECONDS = {
    Interval.ONE_MINUTE: 60,
    Interval.FIVE_MINUTES: 300,
    Interval.FIFTEEN_MINUTES: 900,
    Interval.THIRTY_MINUTES: 1800,
    Interval.ONE_HOUR: 3600,
    Interval.ONE_DAY: 86_400,
    Interval.ONE_WEEK: 604_800,
    Interval.ONE_MONTH: 2_592_000,
}


class MockMarketDataProvider(MarketDataProvider):
    """A random walk dressed up as a market feed."""

    name = "mock"

    def __init__(
        self,
        *,
        base_price: Decimal = Decimal("1400"),
        volatility_bps: Decimal = Decimal("15"),
        spread_bps: Decimal = Decimal("4"),
        tick_interval_seconds: float = 2.0,
        seed: int | None = None,
    ) -> None:
        self.base_price = base_price
        self.volatility_bps = volatility_bps
        self.spread_bps = spread_bps
        self.tick_interval_seconds = tick_interval_seconds

        # A seed makes the walk reproducible, which tests rely on.
        self._random = random.Random(seed)
        self._price = base_price
        self._session_open = base_price
        self._day_high = base_price
        self._day_low = base_price
        self._volume = 0

    @classmethod
    def from_settings(cls) -> "MockMarketDataProvider":
        return cls(
            base_price=settings.MOCK_BASE_PRICE,
            volatility_bps=settings.MOCK_VOLATILITY_BPS,
            spread_bps=settings.MOCK_SPREAD_BPS,
            tick_interval_seconds=settings.MOCK_TICK_INTERVAL_SECONDS,
            seed=settings.MOCK_SEED,
        )

    # -- capabilities ----------------------------------------------------

    @property
    def capabilities(self) -> ProviderCapabilities:
        return ProviderCapabilities(
            name=self.name,
            supports_quotes=True,
            supports_historical=True,
            # Synthesised, not observed -- but genuinely present.
            supports_bid_ask=True,
            supports_live_stream=True,
            is_delayed=False,
            quote_delay_minutes=0,
            requires_credentials=False,
            is_mock=True,
            supported_intervals=list(_INTERVAL_SECONDS),
            limitations=[
                "SIMULATED DATA: prices are generated by a random walk and "
                "have no relationship to the real market.",
                "Bid and ask are synthesised from a configured spread, not "
                "taken from a real order book.",
                "Historical candles are generated on request and are not "
                "stable between calls.",
                "For development and testing only. Never rely on these "
                "numbers for anything.",
            ],
        )

    # -- the walk --------------------------------------------------------

    def _advance(self) -> Decimal:
        """Take one random step and update the session statistics."""
        drift_bps = Decimal(str(self._random.gauss(0, float(self.volatility_bps))))
        self._price = to_money(self._price * (1 + drift_bps / _BPS))

        # Keep the walk from wandering somewhere absurd over a long session.
        floor = self.base_price / 2
        ceiling = self.base_price * 2
        self._price = max(floor, min(ceiling, self._price))

        self._day_high = max(self._day_high, self._price)
        self._day_low = min(self._day_low, self._price)
        self._volume += self._random.randint(100, 5000)
        return self._price

    def _quote_from(self, symbol: str, exchange: str, price: Decimal) -> Quote:
        half_spread = price * (self.spread_bps / _BPS) / 2
        return Quote(
            symbol=symbol.upper(),
            exchange=exchange.upper(),
            last_price=price,
            bid=to_money(price - half_spread),
            ask=to_money(price + half_spread),
            volume=self._volume,
            timestamp=datetime.now(tz=UTC),
            previous_close=self._session_open,
            day_open=self._session_open,
            day_high=self._day_high,
            day_low=self._day_low,
            currency="INR",
            provider=self.name,
            is_delayed=False,
            is_mock=True,
        )

    # -- interface -------------------------------------------------------

    async def get_current_quote(self, symbol: str, exchange: str) -> Quote:
        return self._quote_from(symbol, exchange, self._advance())

    async def get_historical_candles(
        self,
        symbol: str,
        exchange: str,
        interval: Interval,
        start: datetime | None = None,
        end: datetime | None = None,
        limit: int | None = None,
    ) -> list[Candle]:
        """Generate a plausible-looking series ending now."""
        step = timedelta(seconds=_INTERVAL_SECONDS[interval])
        count = min(limit or 100, 1000)
        finish = end or datetime.now(tz=UTC)

        candles: list[Candle] = []
        price = self._price
        for index in range(count, 0, -1):
            open_price = price
            moves = [
                to_money(open_price * (1 + Decimal(str(self._random.gauss(0, float(self.volatility_bps)))) / _BPS))
                for _ in range(3)
            ]
            close_price = moves[-1]
            candles.append(
                Candle(
                    timestamp=finish - step * index,
                    open=open_price,
                    high=max([open_price, close_price, *moves]),
                    low=min([open_price, close_price, *moves]),
                    close=close_price,
                    volume=self._random.randint(10_000, 500_000),
                )
            )
            price = close_price
        return candles

    async def subscribe_live_data(
        self, symbol: str, exchange: str
    ) -> AsyncIterator[Quote]:
        """Push a fresh quote every ``tick_interval_seconds``.

        Overrides the base implementation, which refuses -- this provider can
        genuinely stream because it manufactures the data.
        """
        logger.info(
            "Mock live stream opened for %s:%s (every %.1fs)",
            exchange,
            symbol,
            self.tick_interval_seconds,
        )
        try:
            while True:
                yield await self.get_current_quote(symbol, exchange)
                await asyncio.sleep(self.tick_interval_seconds)
        except asyncio.CancelledError:
            logger.info("Mock live stream closed for %s:%s", exchange, symbol)
            raise
